export const PROVINCE_API_CALL_REQUEST = "PROVINCE_API_CALL_REQUEST"
export const PROVINCE_API_CALL_SUCCESS = "PROVINCE_API_CALL_SUCCESS"
export const PROVINCE_API_CALL_FAILURE = "PROVINCE_API_CALL_FAILURE"